name: dealhunter
version: 3.1.0+31
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
